site:
  title: signalk-notes-opencpn Manual
  url:  https://nowhere.net
  start_page: signalk-notes-opencpn::index.adoc

content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/formifan2002/signalk-notes-opencpn/edit/master/{path}

ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true  